feat: Introduced single sourcing for edge version
ambianic/ambianic-edge pull request #308
Opened 2021-02-10 03:25 UTC by vickywane

This closes this [issue](https://github.com/ambianic/ambianic-ui/issues/343)

This PR contains changes done to introduce single-sourcing on the edge version number used at runtime and also in API responses.

2021-02-10 09:24 UTC, pep8speaks commented
Hello @vickywane! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`src/ambianic/__init__.py`](https://github.com/ambianic/ambianic-edge/blob/c261039fb461849ef8143b4aeb5399258e0dbfdc/src/ambianic/__init__.py):

> [Line 17:19](https://github.com/ambianic/ambianic-edge/blob/c261039fb461849ef8143b4aeb5399258e0dbfdc/src/ambianic/__init__.py#L17): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator

2021-02-10 10:11 UTC, vickywane commented
@ivelin This is looking good for merging.

2021-02-10 19:42 UTC, ivelin requested changes
Looks mostly good. Please add a few unit tests to cover the new features for core versioning and the updated status REST API.

2021-02-10 19:42 UTC, ivelin commented on src/setup.py
> +setup(
@vickywane we are using the [setup.cfg](https://github.com/ambianic/ambianic-edge/blob/master/src/setup.cfg) mechanism for declaring metadata including version. setup.py reads it automatically. No need to set name and version in setup.py. That breaks the way the semantic release script is tied to version updates.

2021-02-10 19:44 UTC, ivelin commented
@vickywane not sure why LGTM triggers JavaScript analysis on this repo. Is it because of the change to the  .theia/settings.json  file? I saw the same issue in one of my new PRs and can't figure out how to turn it off. The LGTM docs point to menus that I can't find. Would be great if you can figure this out. Thank you!

2021-02-10 19:45 UTC, vickywane commented
>@vickywane not sure why LGTM triggers JavaScript analysis on this repo. Is it because of the change to the .theia/settings.json file? I saw the same issue in one of my new PRs and can't figure out how to turn it off. The LGTM docs point to menus that I can't find. Would be great if you can figure this out. Thank you!

Removing `.theia` would be a fix.

2021-02-11 01:11 UTC, ivelin commented
> > @vickywane not sure why LGTM triggers JavaScript analysis on this repo. Is it because of the change to the .theia/settings.json file? I saw the same issue in one of my new PRs and can't figure out how to turn it off. The LGTM docs point to menus that I can't find. Would be great if you can figure this out. Thank you!
> 
> Removing `.theia` would be a fix.

Well, that would mess up the gitpod environment settings.

2021-02-11 01:22 UTC, vickywane commented
> > > @vickywane not sure why LGTM triggers JavaScript analysis on this repo. Is it because of the change to the .theia/settings.json file? I saw the same issue in one of my new PRs and can't figure out how to turn it off. The LGTM docs point to menus that I can't find. Would be great if you can figure this out. Thank you!
> > 
> > 
> > Removing `.theia` would be a fix.
> 
> Well, that would mess up the gitpod environment settings.

Okay, I didn't touch it. 

Can we ignore the test for now? 
I haven't found anything yet.

2021-02-11 02:32 UTC, vickywane commented
@ivelin 

A fix for the Javascript LGTM would come in a separate PR. 
Seems I need to write a configuration file to configure it for python only.

2021-02-11 03:41 UTC, ivelin commented
> > > > @vickywane not sure why LGTM triggers JavaScript analysis on this repo. Is it because of the change to the .theia/settings.json file? I saw the same issue in one of my new PRs and can't figure out how to turn it off. The LGTM docs point to menus that I can't find. Would be great if you can figure this out. Thank you!
> > > 
> > > 
> > > Removing `.theia` would be a fix.
> > 
> > 
> > Well, that would mess up the gitpod environment settings.
> 
> Okay, I didn't touch it.
> 
> Can we ignore the test for now?
> I haven't found anything yet.

Yes, we can ignore this particular check for now.

2021-02-11 04:00 UTC, merged